basePath: /api
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API Gateway cho hệ thống đấu giá trực tuyến - Proxy requests to internal
    services
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API Gateway
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  X-User-Token:
    description: JWT token without Bearer prefix
    in: header
    name: X-User-Token
    type: apiKey
swagger: "2.0"
