spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://ep-morning-snow-a4t3v7lk-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PRODUCT_SERVICE_PORT}

internal:
  key: ${X_AUTH_INTERNAL_KEY}
  
gateway:
  key: ${API_GATEWAY_SECRET}